image: registry.gitlab.com/showcheap/android-ci:react-native

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - echo $PLAYSTORE_KEY > app/google-play-key.json
  - echo $SIGNING_KEYSTORE > app/keystore.properties
  - sed -i 's/\s\+/\n/g' app/keystore.properties
  # Note: Gitlab CI variables show newlines as a space, this will render the storePath as incorrect->Throws error that signingConfig was not found

  - sdkmanager "platforms;android-27"
  - sdkmanager "build-tools;27.0.3"
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - npm install

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

stages:
  - test
  - build
  - deploy

test:
  stage: test
  when: manual
  script:
     - ./gradlew check

build:
  stage: build
  script:
     - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/

deploy:
  stage: deploy
  when: manual
  dependencies:
     - build
  script:
     - ./gradlew publishRelease
