image: registry.gitlab.com/showcheap/android-ci:react-native

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  - npm install


cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

stages:
  - test
  - build

test:
  stage: test
  script:
     - ./gradlew check

build:
  stage: build
  script:
     - ./gradlew assembleRelease
  artifacts:
    expire_in: 1 week
    paths:
      - app/build/outputs/
